# conda env create --file=environment.yml
# conda env update --file=environment.yml --prune
name: BenDayDot

channels:
  - defaults
  - anaconda
  - conda-forge

dependencies:
  - numpy
  - notebook
  - ipywidgets
  - pillow
  - pip
  # - pip: